package day44_exceptions;

public class BadArray {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		int[] number= {1,2,3};
		
		try {
			for (int i= 0; i<= number.length;i++) {
			
			System.out.println(number[i]);
			
			}
		}

		catch (Exception e) {
		
		
		
		}
		
		System.out.println("My name is Gulhan");
	}

}
